### ISSUE TITLE
Problems in zfs-properties.t and zpool-properties.t

### ISSUE THREAD

**Issue by morrone** [chaos/nodediag#15]
There is at least one issue, and possibly a couple of issues shared by zfs-properties.t and zpool-properties.t.

First of all, both scripts have calls to "diag_plan_skip" before the "diag_handle_args" call. But diag_handle_args _must_ be called before things like diag_plan_skip, otherwise it will break the output of "nodediag -c". It looks like there was an attempt to address that issue by redirecting the output of the early diag_plan_skip calls to stderr, but the proper fix is to move the calls to after the call to diag_handle_args.

Once that is done, we should have a test (not a diag_* check, just a generic shell conditional) for the existence of the "zfs" or "zpool" command as the first thing that happens in the relevant diagconfig() command. If "zfs" or "zpool" is not found, a message to stdout of the form "# zfs command not found" should be output, and then exit early from diagconfig().

My next concern is for the foreach_*_and_property() functions in both test files. Is it our intention to just ignore missing pools or filesystems? Is it our intent to ignore pools for which we have no configuration?

**Comment by ofaaland** [comment]
> First of all, both scripts have calls to "diag_plan_skip" before the "diag_handle_args" call. But diag_handle_args must be called before things like diag_plan_skip, otherwise it will break the output of "nodediag -c". It looks like there was an attempt to address that issue by redirecting the output of the early diag_plan_skip calls to stderr, but the proper fix is to move the calls to after the call to diag_handle_args.
Thanks for noticing that.  Fixed.

> Once that is done, we should have a test (not a diag_* check, just a generic shell conditional) for the existence of the "zfs" or "zpool" command as the first thing that happens in the relevant diagconfig() command. If "zfs" or "zpool" is not found, a message to stdout of the form "# zfs command not found" should be output, and then exit early from diagconfig().
Fixed.

> My next concern is for the foreach_*_and_property() functions in both test files. Is it our intention to just ignore missing pools or filesystems?
Yes, but this was a little tricky and suggestions are welcome.  The issue is that at boot time when nodediag is run, pools are not imported and therefore pools and datasets are not available to check their properties.  These checks are run later by the resource agent to do the "real" check that we depend on.   So the logic was that we should not complain about missing pools/datasets to prevent interfering with the boot-time nodediag run.

> Is it our intent to ignore pools for which we have no configuration?
Yes, that is the intent.  This is partially because that is consistent with other tests as far as I am aware.  It is also because I wanted it to be consistent with the behavior of the zfs property test, where we definitely want to ignore datasets without a configuration because there will always be a root dataset which is unused on our Lustre systems.

**Comment by morrone** [comment]
> Yes, but this was a little tricky and suggestions are welcome.

I don't think I have any good suggestions. :) I'm fine with just the patch you created in pr #16.
